application: gae-user-profiles
version: 1
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "3d"

handlers:
- url: .*
  script: main.app
  secure: optional

libraries:
- name: webapp2
  version: "2.5.1"
- name: ssl
  version: latest
