application: gae-auth-123
version: 1
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "3d"

handlers:
- url: .*
  script: main.app
  secure: optional

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
